### ISSUE TITLE
check Pmax value for TOIs

### ISSUE THREAD

**Issue by hiremasa** [hiremasa/ytps#30]

**Comment by hiremasa** [comment]
@jpdeleon 
Here is the result: https://github.com/hiremasa/ytps/blob/results/output/TOI_Pmax/all_df.csv

**Comment by jpdeleon** [comment]
Great thanks! Note that column names have TOIxxxSECTORNone so probably there are duplicate TOI with different sector number that were overwritten.

**Comment by hiremasa** [comment]
Let me check

**Comment by hiremasa** [comment]
TOIxxxSECTOR"None" is mainly because I did not give command line args for the sector to sector number.
When there are duplicate TOI with different sector, oldest one is selected.

**Comment by hiremasa** [comment]
I also upload CSV file with sorted Pmax just in case: https://github.com/hiremasa/ytps/blob/results/output/TOI_Pmax/all_df_sort_pmax.csv

**Comment by jpdeleon** [comment]
OK thanks!
