### ISSUE TITLE
make pipeline figure

### ISSUE THREAD

**Issue by hiremasa** [hiremasa/ytps#5]
make pipeline figure referring to [this paper](https://arxiv.org/pdf/1810.04074.pdf)

**Comment by hiremasa** [comment]
i made GLS one please check it
![image](https://user-images.githubusercontent.com/61959411/137539885-7c49701a-ca5d-4bac-9504-e6a3c08e775b.png)

**Comment by jpdeleon** [comment]
Looks correct.
